
class TestCDS:

    def testMakeDebris(self):
        debris = Debris( s,,,, )
        debris...


    def testCollide(self):
        deb1 = ...
        deb2 = ...
        t0 = tues...
        t1 = thursday ...
        deb1.minDistTo(deb2,t0,t1)